package Main;

import Features.Initialize;
import Features.Macros;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import javax.swing.JTextField;

public class KeyConfigBoard extends javax.swing.JFrame {

    public KeyConfigBoard() {
        initComponents();

        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                KeyConfigBoard.this.setVisible(false);
            }
        });

        selected = new boolean[Macros.NUMBER_OF_MACROS];
        textFields = new JTextField[Macros.NUMBER_OF_MACROS];
        textFields[Macros.FIRST_SKILL_INDEX] = tfFirstSkill;
        textFields[Macros.SECOND_SKILL_INDEX] = tfSecondSkill;
        textFields[Macros.THIRD_SKILL_INDEX] = tfThirdSkill;
        textFields[Macros.ULTIMATE_SKILL_INDEX] = tfUltimate;
        textFields[Macros.BLINK_INDEX] = tfBlink;
        textFields[Macros.ATTACK_INDEX] = tfAttack;
        textFields[Macros.STOP_INDEX] = tfStop;
        textFields[Macros.FOCUS_INDEX] = tfFocus;
        textFields[Macros.SOUND_TOGGLE_INDEX] = tfSound;
        textFields[Macros.MUSIC_TOGGLE_INDEX] = tfMusic;
        textFields[Macros.SAVE_INDEX] = tfSave;
        textFields[Macros.SKILL_TOGGLE_INDEX] = tfSkillToggle;
        textFields[Macros.FIRST_SKILL_BONUS_TOGGLE_INDEX] = tfFirstSkillBonus;
        textFields[Macros.SECOND_SKILL_BONUS_TOGGLE_INDEX] = tfSecondSkillBonus;
        textFields[Macros.THIRD_SKILL_BONUS_TOGGLE_INDEX] = tfThirdSkillBonus;
        textFields[Macros.ULTIMATE_SKILL_BONUS_TOGGLE_INDEX] = tfUltimateBonus;
        textFields[Macros.PAUSE_INDEX] = tfPause;

        for (int i = 0; i < textFields.length; i++) {
            textFields[i].setFocusTraversalKeysEnabled(false);
        }

        macros = new Macros();
        clearSelect();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      tfSave = new javax.swing.JTextField();
      tfMusic = new javax.swing.JTextField();
      tfSound = new javax.swing.JTextField();
      tfFocus = new javax.swing.JTextField();
      tfStop = new javax.swing.JTextField();
      tfAttack = new javax.swing.JTextField();
      tfBlink = new javax.swing.JTextField();
      tfUltimate = new javax.swing.JTextField();
      tfThirdSkill = new javax.swing.JTextField();
      tfSecondSkill = new javax.swing.JTextField();
      tfFirstSkill = new javax.swing.JTextField();
      jLabel1 = new javax.swing.JLabel();
      jLabel2 = new javax.swing.JLabel();
      jLabel3 = new javax.swing.JLabel();
      jLabel4 = new javax.swing.JLabel();
      jLabel5 = new javax.swing.JLabel();
      jLabel9 = new javax.swing.JLabel();
      jLabel8 = new javax.swing.JLabel();
      jLabel7 = new javax.swing.JLabel();
      jLabel13 = new javax.swing.JLabel();
      jLabel14 = new javax.swing.JLabel();
      jLabel12 = new javax.swing.JLabel();
      jLabel11 = new javax.swing.JLabel();
      jLabel10 = new javax.swing.JLabel();
      jLabel6 = new javax.swing.JLabel();
      jLabel15 = new javax.swing.JLabel();
      jLabel16 = new javax.swing.JLabel();
      jLabel17 = new javax.swing.JLabel();
      tfFirstSkillBonus = new javax.swing.JTextField();
      tfSecondSkillBonus = new javax.swing.JTextField();
      tfThirdSkillBonus = new javax.swing.JTextField();
      tfUltimateBonus = new javax.swing.JTextField();
      tfSkillToggle = new javax.swing.JTextField();
      bOK = new javax.swing.JButton();
      tfPause = new javax.swing.JTextField();
      jLabel18 = new javax.swing.JLabel();

      setResizable(false);

      tfSave.setEditable(false);
      tfSave.setHorizontalAlignment(javax.swing.JTextField.CENTER);
      tfSave.addMouseListener(new java.awt.event.MouseAdapter() {
         public void mouseClicked(java.awt.event.MouseEvent evt) {
            tfSaveMouseClicked(evt);
         }
      });
      tfSave.addKeyListener(new java.awt.event.KeyAdapter() {
         public void keyReleased(java.awt.event.KeyEvent evt) {
            tfSaveKeyReleased(evt);
         }
      });

      tfMusic.setEditable(false);
      tfMusic.setHorizontalAlignment(javax.swing.JTextField.CENTER);
      tfMusic.addMouseListener(new java.awt.event.MouseAdapter() {
         public void mouseClicked(java.awt.event.MouseEvent evt) {
            tfMusicMouseClicked(evt);
         }
      });
      tfMusic.addKeyListener(new java.awt.event.KeyAdapter() {
         public void keyReleased(java.awt.event.KeyEvent evt) {
            tfMusicKeyReleased(evt);
         }
      });

      tfSound.setEditable(false);
      tfSound.setHorizontalAlignment(javax.swing.JTextField.CENTER);
      tfSound.addMouseListener(new java.awt.event.MouseAdapter() {
         public void mouseClicked(java.awt.event.MouseEvent evt) {
            tfSoundMouseClicked(evt);
         }
      });
      tfSound.addKeyListener(new java.awt.event.KeyAdapter() {
         public void keyReleased(java.awt.event.KeyEvent evt) {
            tfSoundKeyReleased(evt);
         }
      });

      tfFocus.setEditable(false);
      tfFocus.setHorizontalAlignment(javax.swing.JTextField.CENTER);
      tfFocus.addMouseListener(new java.awt.event.MouseAdapter() {
         public void mouseClicked(java.awt.event.MouseEvent evt) {
            tfFocusMouseClicked(evt);
         }
      });
      tfFocus.addKeyListener(new java.awt.event.KeyAdapter() {
         public void keyReleased(java.awt.event.KeyEvent evt) {
            tfFocusKeyReleased(evt);
         }
      });

      tfStop.setEditable(false);
      tfStop.setHorizontalAlignment(javax.swing.JTextField.CENTER);
      tfStop.addMouseListener(new java.awt.event.MouseAdapter() {
         public void mouseClicked(java.awt.event.MouseEvent evt) {
            tfStopMouseClicked(evt);
         }
      });
      tfStop.addKeyListener(new java.awt.event.KeyAdapter() {
         public void keyReleased(java.awt.event.KeyEvent evt) {
            tfStopKeyReleased(evt);
         }
      });

      tfAttack.setEditable(false);
      tfAttack.setHorizontalAlignment(javax.swing.JTextField.CENTER);
      tfAttack.addMouseListener(new java.awt.event.MouseAdapter() {
         public void mouseClicked(java.awt.event.MouseEvent evt) {
            tfAttackMouseClicked(evt);
         }
      });
      tfAttack.addKeyListener(new java.awt.event.KeyAdapter() {
         public void keyReleased(java.awt.event.KeyEvent evt) {
            tfAttackKeyReleased(evt);
         }
      });

      tfBlink.setEditable(false);
      tfBlink.setHorizontalAlignment(javax.swing.JTextField.CENTER);
      tfBlink.addMouseListener(new java.awt.event.MouseAdapter() {
         public void mouseClicked(java.awt.event.MouseEvent evt) {
            tfBlinkMouseClicked(evt);
         }
      });
      tfBlink.addKeyListener(new java.awt.event.KeyAdapter() {
         public void keyReleased(java.awt.event.KeyEvent evt) {
            tfBlinkKeyReleased(evt);
         }
      });

      tfUltimate.setEditable(false);
      tfUltimate.setHorizontalAlignment(javax.swing.JTextField.CENTER);
      tfUltimate.addMouseListener(new java.awt.event.MouseAdapter() {
         public void mouseClicked(java.awt.event.MouseEvent evt) {
            tfUltimateMouseClicked(evt);
         }
      });
      tfUltimate.addKeyListener(new java.awt.event.KeyAdapter() {
         public void keyReleased(java.awt.event.KeyEvent evt) {
            tfUltimateKeyReleased(evt);
         }
      });

      tfThirdSkill.setEditable(false);
      tfThirdSkill.setHorizontalAlignment(javax.swing.JTextField.CENTER);
      tfThirdSkill.addMouseListener(new java.awt.event.MouseAdapter() {
         public void mouseClicked(java.awt.event.MouseEvent evt) {
            tfThirdSkillMouseClicked(evt);
         }
      });
      tfThirdSkill.addKeyListener(new java.awt.event.KeyAdapter() {
         public void keyReleased(java.awt.event.KeyEvent evt) {
            tfThirdSkillKeyReleased(evt);
         }
      });

      tfSecondSkill.setEditable(false);
      tfSecondSkill.setHorizontalAlignment(javax.swing.JTextField.CENTER);
      tfSecondSkill.addMouseListener(new java.awt.event.MouseAdapter() {
         public void mouseClicked(java.awt.event.MouseEvent evt) {
            tfSecondSkillMouseClicked(evt);
         }
      });
      tfSecondSkill.addKeyListener(new java.awt.event.KeyAdapter() {
         public void keyReleased(java.awt.event.KeyEvent evt) {
            tfSecondSkillKeyReleased(evt);
         }
      });

      tfFirstSkill.setEditable(false);
      tfFirstSkill.setHorizontalAlignment(javax.swing.JTextField.CENTER);
      tfFirstSkill.addMouseListener(new java.awt.event.MouseAdapter() {
         public void mouseClicked(java.awt.event.MouseEvent evt) {
            tfFirstSkillMouseClicked(evt);
         }
      });
      tfFirstSkill.addKeyListener(new java.awt.event.KeyAdapter() {
         public void keyReleased(java.awt.event.KeyEvent evt) {
            tfFirstSkillKeyReleased(evt);
         }
      });

      jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
      jLabel1.setText("First Skill");

      jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
      jLabel2.setText("Second Skill");

      jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
      jLabel3.setText("Third Skill");

      jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
      jLabel4.setText("Ultimate");

      jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
      jLabel5.setText("Blink");

      jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
      jLabel9.setText("Focus");

      jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
      jLabel8.setText("Stop");

      jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
      jLabel7.setText("Attack");

      jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
      jLabel13.setText("First Skill Bonus Toggle");

      jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
      jLabel14.setText("Second Skill Bonus Toggle");

      jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
      jLabel12.setText("Save");

      jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
      jLabel11.setText("Music Toggle");

      jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
      jLabel10.setText("Sound Toggle");

      jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
      jLabel6.setText("Hotkey Macro");

      jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
      jLabel15.setText("Third Skill Bonus Toggle");

      jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
      jLabel16.setText("Ultimate Bonus Toggle");

      jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
      jLabel17.setText("Skill Toggle");

      tfFirstSkillBonus.setEditable(false);
      tfFirstSkillBonus.setHorizontalAlignment(javax.swing.JTextField.CENTER);
      tfFirstSkillBonus.setText("jTextField1");
      tfFirstSkillBonus.addMouseListener(new java.awt.event.MouseAdapter() {
         public void mouseClicked(java.awt.event.MouseEvent evt) {
            tfFirstSkillBonusMouseClicked(evt);
         }
      });
      tfFirstSkillBonus.addKeyListener(new java.awt.event.KeyAdapter() {
         public void keyReleased(java.awt.event.KeyEvent evt) {
            tfFirstSkillBonusKeyReleased(evt);
         }
      });

      tfSecondSkillBonus.setEditable(false);
      tfSecondSkillBonus.setHorizontalAlignment(javax.swing.JTextField.CENTER);
      tfSecondSkillBonus.setText("jTextField2");
      tfSecondSkillBonus.addMouseListener(new java.awt.event.MouseAdapter() {
         public void mouseClicked(java.awt.event.MouseEvent evt) {
            tfSecondSkillBonusMouseClicked(evt);
         }
      });
      tfSecondSkillBonus.addKeyListener(new java.awt.event.KeyAdapter() {
         public void keyReleased(java.awt.event.KeyEvent evt) {
            tfSecondSkillBonusKeyReleased(evt);
         }
      });

      tfThirdSkillBonus.setEditable(false);
      tfThirdSkillBonus.setHorizontalAlignment(javax.swing.JTextField.CENTER);
      tfThirdSkillBonus.setText("jTextField3");
      tfThirdSkillBonus.addMouseListener(new java.awt.event.MouseAdapter() {
         public void mouseClicked(java.awt.event.MouseEvent evt) {
            tfThirdSkillBonusMouseClicked(evt);
         }
      });
      tfThirdSkillBonus.addKeyListener(new java.awt.event.KeyAdapter() {
         public void keyReleased(java.awt.event.KeyEvent evt) {
            tfThirdSkillBonusKeyReleased(evt);
         }
      });

      tfUltimateBonus.setEditable(false);
      tfUltimateBonus.setHorizontalAlignment(javax.swing.JTextField.CENTER);
      tfUltimateBonus.setText("jTextField4");
      tfUltimateBonus.addMouseListener(new java.awt.event.MouseAdapter() {
         public void mouseClicked(java.awt.event.MouseEvent evt) {
            tfUltimateBonusMouseClicked(evt);
         }
      });
      tfUltimateBonus.addKeyListener(new java.awt.event.KeyAdapter() {
         public void keyReleased(java.awt.event.KeyEvent evt) {
            tfUltimateBonusKeyReleased(evt);
         }
      });

      tfSkillToggle.setEditable(false);
      tfSkillToggle.setHorizontalAlignment(javax.swing.JTextField.CENTER);
      tfSkillToggle.setText("jTextField5");
      tfSkillToggle.addMouseListener(new java.awt.event.MouseAdapter() {
         public void mouseClicked(java.awt.event.MouseEvent evt) {
            tfSkillToggleMouseClicked(evt);
         }
      });
      tfSkillToggle.addKeyListener(new java.awt.event.KeyAdapter() {
         public void keyReleased(java.awt.event.KeyEvent evt) {
            tfSkillToggleKeyReleased(evt);
         }
      });

      bOK.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
      bOK.setText("OK");
      bOK.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            bOKActionPerformed(evt);
         }
      });

      tfPause.setEditable(false);
      tfPause.setHorizontalAlignment(javax.swing.JTextField.CENTER);
      tfPause.setText("jTextField1");
      tfPause.addMouseListener(new java.awt.event.MouseAdapter() {
         public void mouseClicked(java.awt.event.MouseEvent evt) {
            tfPauseMouseClicked(evt);
         }
      });
      tfPause.addKeyListener(new java.awt.event.KeyAdapter() {
         public void keyReleased(java.awt.event.KeyEvent evt) {
            tfPauseKeyReleased(evt);
         }
      });

      jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
      jLabel18.setText("Pause");

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                  .addContainerGap()
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(jLabel12)
                     .addComponent(jLabel11)
                     .addComponent(jLabel10)
                     .addComponent(jLabel18))
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                     .addComponent(tfPause)
                     .addComponent(tfSound, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                     .addComponent(tfMusic)
                     .addComponent(tfSave))
                  .addGap(18, 18, 18)
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(jLabel8)
                     .addComponent(jLabel9)
                     .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                     .addComponent(tfStop, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                     .addComponent(tfAttack)
                     .addComponent(tfFocus))
                  .addGap(18, 18, 18)
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(jLabel4)
                     .addComponent(jLabel5)
                     .addComponent(jLabel1)
                     .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                           .addComponent(jLabel2)
                           .addComponent(jLabel3))
                        .addComponent(jLabel17)))
                  .addGap(18, 18, 18)
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                     .addComponent(tfFirstSkill)
                     .addComponent(tfSecondSkill)
                     .addComponent(tfThirdSkill)
                     .addComponent(tfUltimate)
                     .addComponent(tfBlink)
                     .addComponent(tfSkillToggle, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE))
                  .addGap(18, 18, 18)
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                           .addComponent(jLabel14)
                           .addComponent(jLabel13)
                           .addComponent(jLabel15)
                           .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                           .addComponent(tfFirstSkillBonus, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                           .addComponent(tfSecondSkillBonus)
                           .addComponent(tfThirdSkillBonus)
                           .addComponent(tfUltimateBonus)))
                     .addComponent(bOK, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
               .addGroup(layout.createSequentialGroup()
                  .addGap(392, 392, 392)
                  .addComponent(jLabel6)))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap(20, Short.MAX_VALUE)
            .addComponent(jLabel6)
            .addGap(29, 29, 29)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                     .addComponent(jLabel1)
                     .addComponent(tfFirstSkill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(jLabel13)
                     .addComponent(tfFirstSkillBonus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                     .addComponent(jLabel2)
                     .addComponent(tfSecondSkill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(jLabel14)
                     .addComponent(tfSecondSkillBonus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                     .addComponent(jLabel3)
                     .addComponent(tfThirdSkill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(jLabel15)
                     .addComponent(tfThirdSkillBonus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                     .addComponent(jLabel4)
                     .addComponent(tfUltimate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(jLabel16)
                     .addComponent(tfUltimateBonus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                           .addComponent(tfBlink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                           .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                           .addComponent(tfSkillToggle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                           .addComponent(jLabel17)))
                     .addComponent(bOK, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
               .addGroup(layout.createSequentialGroup()
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                     .addComponent(jLabel10)
                     .addComponent(tfSound, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(jLabel7))
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                     .addComponent(jLabel11)
                     .addComponent(tfMusic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(jLabel8))
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                     .addComponent(jLabel12)
                     .addComponent(tfSave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(jLabel9))
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                     .addComponent(tfPause, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(jLabel18)))
               .addGroup(layout.createSequentialGroup()
                  .addComponent(tfAttack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                  .addComponent(tfStop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                  .addComponent(tfFocus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

    private void tfFirstSkillMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfFirstSkillMouseClicked
        promptChangeRequest(Macros.FIRST_SKILL_INDEX);
    }//GEN-LAST:event_tfFirstSkillMouseClicked

    private void tfFirstSkillKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfFirstSkillKeyReleased
        keyReleased(evt, Macros.FIRST_SKILL_INDEX);
    }//GEN-LAST:event_tfFirstSkillKeyReleased

    private void tfSecondSkillMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfSecondSkillMouseClicked
        promptChangeRequest(Macros.SECOND_SKILL_INDEX);
    }//GEN-LAST:event_tfSecondSkillMouseClicked

    private void tfThirdSkillMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfThirdSkillMouseClicked
        promptChangeRequest(Macros.THIRD_SKILL_INDEX);
    }//GEN-LAST:event_tfThirdSkillMouseClicked

    private void tfUltimateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfUltimateMouseClicked
        promptChangeRequest(Macros.ULTIMATE_SKILL_INDEX);
    }//GEN-LAST:event_tfUltimateMouseClicked

    private void tfBlinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfBlinkMouseClicked
        promptChangeRequest(Macros.BLINK_INDEX);
    }//GEN-LAST:event_tfBlinkMouseClicked

    private void tfSecondSkillKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfSecondSkillKeyReleased
        keyReleased(evt, Macros.SECOND_SKILL_INDEX);
    }//GEN-LAST:event_tfSecondSkillKeyReleased

    private void tfThirdSkillKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfThirdSkillKeyReleased
        keyReleased(evt, Macros.THIRD_SKILL_INDEX);
    }//GEN-LAST:event_tfThirdSkillKeyReleased

    private void tfUltimateKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfUltimateKeyReleased
        keyReleased(evt, Macros.ULTIMATE_SKILL_INDEX);
    }//GEN-LAST:event_tfUltimateKeyReleased

    private void tfBlinkKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfBlinkKeyReleased
        keyReleased(evt, Macros.BLINK_INDEX);
    }//GEN-LAST:event_tfBlinkKeyReleased

    private void tfAttackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfAttackMouseClicked
        promptChangeRequest(Macros.ATTACK_INDEX);
    }//GEN-LAST:event_tfAttackMouseClicked

    private void tfAttackKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfAttackKeyReleased
        keyReleased(evt, Macros.ATTACK_INDEX);
    }//GEN-LAST:event_tfAttackKeyReleased

    private void tfStopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfStopMouseClicked
        promptChangeRequest(Macros.STOP_INDEX);
    }//GEN-LAST:event_tfStopMouseClicked

    private void tfStopKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfStopKeyReleased
        keyReleased(evt, Macros.STOP_INDEX);
    }//GEN-LAST:event_tfStopKeyReleased

    private void tfFocusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfFocusMouseClicked
        promptChangeRequest(Macros.FOCUS_INDEX);
    }//GEN-LAST:event_tfFocusMouseClicked

    private void tfFocusKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfFocusKeyReleased
        keyReleased(evt, Macros.FOCUS_INDEX);
    }//GEN-LAST:event_tfFocusKeyReleased

    private void tfSaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfSaveMouseClicked
        promptChangeRequest(Macros.SAVE_INDEX);
    }//GEN-LAST:event_tfSaveMouseClicked

    private void tfSaveKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfSaveKeyReleased
        keyReleased(evt, Macros.SAVE_INDEX);
    }//GEN-LAST:event_tfSaveKeyReleased

    private void tfMusicMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfMusicMouseClicked
        promptChangeRequest(Macros.MUSIC_TOGGLE_INDEX);
    }//GEN-LAST:event_tfMusicMouseClicked

    private void tfMusicKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfMusicKeyReleased
        keyReleased(evt, Macros.MUSIC_TOGGLE_INDEX);
    }//GEN-LAST:event_tfMusicKeyReleased

    private void tfSoundMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfSoundMouseClicked
        promptChangeRequest(Macros.SOUND_TOGGLE_INDEX);
    }//GEN-LAST:event_tfSoundMouseClicked

    private void tfSoundKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfSoundKeyReleased
        keyReleased(evt, Macros.SOUND_TOGGLE_INDEX);
    }//GEN-LAST:event_tfSoundKeyReleased

    private void tfFirstSkillBonusKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfFirstSkillBonusKeyReleased
        keyReleased(evt, Macros.FIRST_SKILL_BONUS_TOGGLE_INDEX);
    }//GEN-LAST:event_tfFirstSkillBonusKeyReleased

    private void tfFirstSkillBonusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfFirstSkillBonusMouseClicked
        promptChangeRequest(Macros.FIRST_SKILL_BONUS_TOGGLE_INDEX);
    }//GEN-LAST:event_tfFirstSkillBonusMouseClicked

    private void tfSecondSkillBonusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfSecondSkillBonusMouseClicked
        promptChangeRequest(Macros.SECOND_SKILL_BONUS_TOGGLE_INDEX);
    }//GEN-LAST:event_tfSecondSkillBonusMouseClicked

    private void tfSecondSkillBonusKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfSecondSkillBonusKeyReleased
        keyReleased(evt, Macros.SECOND_SKILL_BONUS_TOGGLE_INDEX);
    }//GEN-LAST:event_tfSecondSkillBonusKeyReleased

    private void tfThirdSkillBonusKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfThirdSkillBonusKeyReleased
        keyReleased(evt, Macros.THIRD_SKILL_BONUS_TOGGLE_INDEX);
    }//GEN-LAST:event_tfThirdSkillBonusKeyReleased

    private void tfThirdSkillBonusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfThirdSkillBonusMouseClicked
        promptChangeRequest(Macros.THIRD_SKILL_BONUS_TOGGLE_INDEX);
    }//GEN-LAST:event_tfThirdSkillBonusMouseClicked

    private void tfUltimateBonusKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfUltimateBonusKeyReleased
        keyReleased(evt, Macros.ULTIMATE_SKILL_BONUS_TOGGLE_INDEX);
    }//GEN-LAST:event_tfUltimateBonusKeyReleased

    private void tfUltimateBonusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfUltimateBonusMouseClicked
        promptChangeRequest(Macros.ULTIMATE_SKILL_BONUS_TOGGLE_INDEX);
    }//GEN-LAST:event_tfUltimateBonusMouseClicked

    private void tfSkillToggleKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfSkillToggleKeyReleased
        keyReleased(evt, Macros.SKILL_TOGGLE_INDEX);
    }//GEN-LAST:event_tfSkillToggleKeyReleased

    private void tfSkillToggleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfSkillToggleMouseClicked
        promptChangeRequest(Macros.SKILL_TOGGLE_INDEX);
    }//GEN-LAST:event_tfSkillToggleMouseClicked

    private void bOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bOKActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_bOKActionPerformed

   private void tfPauseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfPauseMouseClicked
      promptChangeRequest(Macros.PAUSE_INDEX);
   }//GEN-LAST:event_tfPauseMouseClicked

   private void tfPauseKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfPauseKeyReleased
      keyReleased(evt, Macros.PAUSE_INDEX);
   }//GEN-LAST:event_tfPauseKeyReleased

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton bOK;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel10;
   private javax.swing.JLabel jLabel11;
   private javax.swing.JLabel jLabel12;
   private javax.swing.JLabel jLabel13;
   private javax.swing.JLabel jLabel14;
   private javax.swing.JLabel jLabel15;
   private javax.swing.JLabel jLabel16;
   private javax.swing.JLabel jLabel17;
   private javax.swing.JLabel jLabel18;
   private javax.swing.JLabel jLabel2;
   private javax.swing.JLabel jLabel3;
   private javax.swing.JLabel jLabel4;
   private javax.swing.JLabel jLabel5;
   private javax.swing.JLabel jLabel6;
   private javax.swing.JLabel jLabel7;
   private javax.swing.JLabel jLabel8;
   private javax.swing.JLabel jLabel9;
   private javax.swing.JTextField tfAttack;
   private javax.swing.JTextField tfBlink;
   private javax.swing.JTextField tfFirstSkill;
   private javax.swing.JTextField tfFirstSkillBonus;
   private javax.swing.JTextField tfFocus;
   private javax.swing.JTextField tfMusic;
   private javax.swing.JTextField tfPause;
   private javax.swing.JTextField tfSave;
   private javax.swing.JTextField tfSecondSkill;
   private javax.swing.JTextField tfSecondSkillBonus;
   private javax.swing.JTextField tfSkillToggle;
   private javax.swing.JTextField tfSound;
   private javax.swing.JTextField tfStop;
   private javax.swing.JTextField tfThirdSkill;
   private javax.swing.JTextField tfThirdSkillBonus;
   private javax.swing.JTextField tfUltimate;
   private javax.swing.JTextField tfUltimateBonus;
   // End of variables declaration//GEN-END:variables
    private boolean[] selected;
    private JTextField[] textFields;
    private Macros macros;
    private static final String CHANGE_HOT_KEY = "Assign New Key";
    private static final String INVALID_HOT_KEY = "Reserved Key";
    private static final String UNDEFINED_HOT_KEY = "Undefined Key";

    private void keyReleased(KeyEvent evt, int textFieldIndex) {
        if (selected[textFieldIndex]) {
            int key = evt.getKeyCode();
            if (Macros.RESERVED().contains(key)) {
                textFields[textFieldIndex].setText(INVALID_HOT_KEY);
            } else {
                textFields[textFieldIndex].setText(KeyEvent.getKeyText(key).toUpperCase());
                macros.hotKeys()[textFieldIndex] = key;
                for (int i = 0; i < Macros.NUMBER_OF_MACROS; i++) {
                    if ((i != textFieldIndex) && (macros.hotKeys()[i] == key)) {
                        macros.hotKeys()[i] = KeyEvent.VK_UNDEFINED;
                    }
                }
                clearSelect();
            }
        }
    }

    private void promptChangeRequest(int textFieldIndex) {
        clearSelect();
        textFields[textFieldIndex].setText(CHANGE_HOT_KEY);
        selected[textFieldIndex] = true;
    }

    private void clearSelect() {
        for (int i = 0; i < Macros.NUMBER_OF_MACROS; i++) {
            selected[i] = false;
            if (macros.hotKeys()[i] != KeyEvent.VK_UNDEFINED) {
                textFields[i].setText(KeyEvent.getKeyText(macros.hotKeys()[i]));
            } else {
                textFields[i].setText(UNDEFINED_HOT_KEY);
            }
        }
    }

    protected Macros macros() {
        return macros;
    }
}
